<form action="add" method="POST">
    <div class="container">
        <h3 class="mt-4">Agregar nueva moto</h3>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="form-group">
                    <label for="marca">Marca</label>
                    <input required name="marca" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="modelo">Modelo</label>
                    <select name="modelo" id="modelo" class="form-control">
                        <?php 
                        foreach ($modelos as $mod) { ?>
                            <option value="<?php echo $mod->modelo?>"><?php echo $mod->modelo ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="anio">Año</label>
                    <input required name="anio" type="number" class="form-control">
                </div>
                <div class="form-group">
                    <label for="precio">Precio</label>
                    <input required name="precio" type="number" class="form-control">
                </div>
            </div>
        </div>
        <div class="container">
            <button type="submit" class="btn btn-primary mt-3">Agregar</button>
        </div>
    </div>
</form>