<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="auth">
        <div class="form-group">
            <label for="username">Usuario</label>
            <input type="text" required class="form-control" id="username" name="username">
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <button type="submit" class="btn btn-primary mt-3">Ingresar</button>
    </form>
</div>